merge_protections:
  - name: require-approval-mp
    if:
      - base=main
    success_conditions:
      - "#approved-reviews-by>=1"
pull_request_rules:
  - name: auto-merge attempt
    conditions:
      - base=main
    actions:
      merge:
        method: merge
