queue_rules:
  - name: default
    merge_conditions:
      - check-success=hold-gate
pull_request_rules:
  - name: queue on base main
    conditions:
      - base=main
    actions:
      queue:
        name: default
